In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df = pd.read_csv('covid_toy.csv')

In [4]:


df.head()



age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [5]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                test_size=0.2)

In [7]:
X_train

age  gender  fever   cough       city
53   83    Male   98.0    Mild      Delhi
93   27    Male  100.0    Mild    Kolkata
84   69  Female   98.0  Strong     Mumbai
94   79    Male    NaN  Strong    Kolkata
38   49  Female  101.0    Mild      Delhi
..  ...     ...    ...     ...        ...
99   10  Female   98.0  Strong    Kolkata
13   64    Male  102.0    Mild  Bangalore
1    27    Male  100.0    Mild      Delhi
7    20  Female    NaN  Strong     Mumbai
43   22  Female   99.0    Mild  Bangalore

[80 rows x 5 columns]

In [8]:
si = SimpleImputer()

# Fit only on training data
X_train_fever = si.fit_transform(X_train[['fever']])

# Transform test data using the same imputer
X_test_fever = si.transform(X_test[['fever']])

In [9]:
X_train_fever

array([[ 98.        ],
       [100.        ],
       [ 98.        ],
       [100.78873239],
       [101.        ],
       [104.        ],
       [103.        ],
       [102.        ],
       [100.        ],
       [104.        ],
       [102.        ],
       [100.        ],
       [101.        ],
       [103.        ],
       [101.        ],
       [102.        ],
       [101.        ],
       [101.        ],
       [100.78873239],
       [104.        ],
       [ 99.        ],
       [100.78873239],
       [104.        ],
       [102.        ],
       [100.78873239],
       [100.78873239],
       [104.        ],
       [102.        ],
       [ 98.        ],
       [100.        ],
       [ 98.        ],
       [101.        ],
       [100.78873239],
       [ 98.        ],
       [ 99.        ],
       [100.        ],
       [103.        ],
       [ 99.        ],
       [101.        ],
       [103.        ],
       [104.        ],
       [100.        ],
       [103.        ],
       [ 98

In [10]:
X_train_fever.shape

(80, 1)

In [11]:
# Define the order of categories
oe = OrdinalEncoder(categories=[['Mild','Strong']])

# Fit only on training data
X_train_cough = oe.fit_transform(X_train[['cough']])

# Use the same encoder to transform the test data
X_test_cough = oe.transform(X_test[['cough']])

In [12]:
X_train_cough

array([[0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],

In [13]:
X_train_cough.shape

(80, 1)

In [15]:
# Create encoder
ohe = OneHotEncoder(drop='first', sparse_output=False)

# Fit on training data
X_train_gender_city = ohe.fit_transform(X_train[['gender', 'city']])

# Transform test data using the same encoder
X_test_gender_city = ohe.transform(X_test[['gender', 'city']])

In [16]:
X_train_gender_city

array([[1., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [1., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],


In [17]:
X_train_gender_city.shape

(80, 4)

In [18]:


# Extracting Age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape



(80, 1)

In [19]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
# also the test data
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

X_train_transformed.shape

(80, 7)

In [20]:
from sklearn.compose import ColumnTransformer



In [21]:
transformer = ColumnTransformer(transformers=[
    ('tnf1', SimpleImputer(), ['fever']),  
    ('tnf2', OrdinalEncoder(categories=[['Mild','Strong']]), ['cough']),  
    ('tnf3', OneHotEncoder(drop='first', sparse_output=False), ['gender','city'])  
], remainder='passthrough')

In [22]:


transformer.fit_transform(X_train)



array([[ 98.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  83.        ],
       [100.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  27.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  69.        ],
       [100.78873239,   1.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  79.        ],
       [101.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  49.        ],
       [104.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  54.        ],
       [103.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  60.        ],
       [102.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  69.        ],
       [100.        ,   1.        ,   0.        ,   0.        ,
          1.    

In [23]:


transformer.fit_transform(X_train).shape



(80, 7)

In [24]:
transformer.transform(X_test)

array([[100.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  55.        ],
       [101.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  64.        ],
       [101.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  15.        ],
       [103.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  46.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  25.        ],
       [ 99.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  25.        ],
       [102.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   5.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  81.        ],
       [ 99.        ,   0.        ,   1.        ,   1.        ,
          0.    

In [25]:
transformer.transform(X_test).shape

(20, 7)