In [6]:
import pickle
import numpy as np

In [7]:

# encode madel covert to decode 
ohe_sex = pickle.load(open('models/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('models/ohe_embarked.pkl','rb'))
clf = pickle.load(open('models/clf.pkl','rb'))



In [8]:
# Assume user input
# Pclass/gender/age/SibSp/Parch/Fare/Embarked
test_input = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'],dtype=object).reshape(1,7)

In [9]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [11]:
gender_df = pd.DataFrame({'gender': ['male']})
test_input_gender_encoded = ohe_sex.transform(gender_df)

NameError: name 'pd' is not defined

In [12]:
import pandas as pd

In [13]:
# gender অংশ DataFrame এ নেয়া
gender_df = pd.DataFrame({'gender': ['male']})

In [15]:
sex_df = pd.DataFrame({'Sex': ['male']})   # অবশ্যই 'Sex' লিখবে
test_input_sex = ohe_sex.transform(sex_df)

In [16]:
test_input_sex

array([[0., 1.]])

In [17]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [18]:
test_input_embarked

array([[0., 0., 1.]])

In [19]:
test_input_age = test_input[:,2].reshape(1,1)

In [20]:


test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)



In [21]:
test_input_transformed.shape

(1, 10)

In [22]:
clf.predict(test_input_transformed)

array([0])

In [23]:
prediction = clf.predict(test_input_transformed)
print("Prediction (1=Survived, 0=Not Survived):", prediction[0])


Prediction (1=Survived, 0=Not Survived): 0
